---
info:
  title: shell_login_attributes
attributes:
  - name: shell_password
    required: true
    schema:
      maxLength: 32
      minLength: 4
      type: string
    x-ctype: string
    x-broadcast: false
    x-default: "zephyr"
    x-prepare: false
    x-readable: false
    x-savable: true
    x-writable: true
    x-hide-in-show: true
    x-show-on-change: false
    summary: Password to login and use the shell
  - name: shell_session_timeout
    summary: Time before a login session will expire (in minutes). Set to 0 to disable.
    required: true
    schema:
      minimum: 0
      maximum: 255
      type: integer
    x-ctype: uint8_t
    x-default: 5
    x-readable: true
    x-savable: true
    x-writable: true
